### ISSUE TITLE
localization plugin will lose the text content that decorator a tag before the line

### ISSUE THREAD

**Issue by ColinCollins** [IgniteUI/typedoc-plugin-localization#34]
Hi, when I use your plugin with the typedoc example, I find the annotation will lose when i decorate a tag before the annotation line.
![image](https://user-images.githubusercontent.com/35832931/53225790-17a1be80-36b4-11e9-8314-5a3470bf1f0d.png)
![image](https://user-images.githubusercontent.com/35832931/53225864-546db580-36b4-11e9-87bc-790c6e3964d9.png)
Do you think this is a bug? If so, hope you can fix it, Thx~

**Comment by Aleksandyr** [comment]
@ColinCollins I think this is how **typedoc** works. Why don't you try to move that decoration below the comment you would like to show.
Under the hood when the parser gets the comment it parses it into several sections. 
The first few lines are for the comment itself and when the parser finds a **decoration** or **parameter** it gets it as a part of the **decorator** or **parameter**.

**Comment by ColinCollins** [comment]
Firstly, Thx for your feedback @Aleksandyr .
Second, when I use **typedoc** constructed the docs straightly, that kind of decorator will be detected perfectly. so I think that the localization parses result should keep content with typedoc generates as the same. That just a suggestion.
I'm not sure your plugin on how to get the Object from the typedoc, so maybe you are right.

**Comment by Aleksandyr** [comment]
@ColinCollins I assume that you have missed to enable the exports for **tags** In order to achieve this you have to include into your command **--tags** option. This would export all the tags you have referred into your comments. Once you enable that option and trigger the exportation of the **JSON** file you would observe that your **JSON** would have the following structure.

```json
"SubClassB": {
    "tags": {
        "comment: {
              "text": "The constructor of the original class should be overwritten"
         },
         tagName: "test"
     }
    "comment" { 
       "shortText": "This is a class that extends another class."
    }
}
````

The plugin just takes the comment provided by **typedoc** and creates a **JSON** which corresponds to the structure of the comment that **typedoc** builds.
I have tested that same structure of the comment you have without the plugin and the result was the same.

I hope that now it is clearer for you. Please verify that you have went through the whole [README ](https://github.com/IgniteUI/typedoc-plugin-localization#arguments) which describes every option that the plugin exposes.

**Comment by ColinCollins** [comment]
Oh, my bad, Thx for your time.
